name: Deploy example
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: 47ng/actions-clever-cloud@v1.3.1
        with:
          appID: app_d32973d1-4ca4-42cc-ae69-168117b066ea
        env:
          CLEVER_TOKEN: ${{ secrets.CLEVER_TOKEN }}
          CLEVER_SECRET: ${{ secrets.CLEVER_SECRET }}

